# Spring properties
# Set Application name as catalog-service
spring:
  application:
     name: catalog-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2225   # HTTP (Tomcat) port